# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
# font_family MesloLGS Nerd Font Mono
font_size 14.0
window_margin_width 5
cursor_trail 10
cursor_trail_decay 0.1 0.2
cursor_shape beam
# background_opacity 0.9
# Cannot get this work with the blur my shell extension on gnome/wayland
background_blur 1
hide_window_decorations yes

# Required because I can't set the default shell on my work laptop
shell fish

# BEGIN_KITTY_FONTS
# use `kitten choose-font` to browse
font_family      family="MesloLGM Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
